// port-lint: source stream/try_stream/mod.rs
@file:OptIn(kotlin.experimental.ExperimentalObjCRefinement::class)

package io.github.kotlinmania.futures

import kotlin.native.HiddenFromObjC

/**
 * Executes an asynchronous action for each item and flattens the resulting [Future].
 */
@HiddenFromObjC
public fun <T, E, R> TryStream<T, E>.andThen(transform: (T) -> Future<Try<R, E>>): TryStreamAndThen<T, E, R> =
    TryStreamAndThen.new(this, transform)

/**
 * Handles errors generated by this stream by returning a new [Future].
 */
@HiddenFromObjC
public fun <T, E, R> TryStream<T, E>.orElse(transform: (E) -> Future<Try<T, R>>): TryStreamOrElse<T, E, R> =
    TryStreamOrElse.new(this, transform)

/**
 * Creates a future that attempts to resolve to the next item of this stream.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.tryNext(): TryNext<T, E> = TryNext.new(this)

/**
 * Filters the items produced by this stream according to the provided asynchronous predicate.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.tryFilter(predicate: (T) -> Future<Boolean>): TryFilter<T, E> =
    TryFilter.new(this, predicate)

/**
 * Filters and maps the items produced by this stream using the provided asynchronous closure.
 */
@HiddenFromObjC
public fun <T, E, R> TryStream<T, E>.tryFilterMap(transform: (T) -> Future<Try<R?, E>>): TryStreamFilterMap<T, E, R> =
    TryStreamFilterMap.new(this, transform)

/**
 * Flattens a stream of try-streams into a single stream.
 */
@HiddenFromObjC
public fun <T, E> TryStream<TryStream<T, E>, E>.tryFlatten(): TryStreamFlatten<T, E> =
    TryStreamFlatten.new(this)

/**
 * Collects all items of a stream into a list, stopping on first error.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.tryCollect(): TryCollect<T, E> = TryCollect.new(this)

/**
 * Concatenates all list items of a stream into a single list, stopping on first error.
 */
@HiddenFromObjC
public fun <T, E> TryStream<List<T>, E>.tryConcat(): TryConcat<T, E> = TryConcat.new(this)

/**
 * Executes an accumulator over all items of the stream, stopping on first error.
 */
@HiddenFromObjC
public fun <T, E, Acc> TryStream<T, E>.tryFold(
    initial: Acc,
    fold: (Acc, T) -> Future<Try<Acc, E>>,
): TryFold<T, E, Acc> = TryFold.new(this, fold, initial)

/**
 * Runs an asynchronous action for each item in the stream, stopping on first error.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.tryForEach(action: (T) -> Future<Try<Unit, E>>): TryStreamForEach<T, E> =
    TryStreamForEach.new(this, action)

/**
 * Skips items produced by this stream while the predicate resolves to true.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.trySkipWhile(predicate: (T) -> Future<Try<Boolean, E>>): TrySkipWhile<T, E> =
    TrySkipWhile.new(this, predicate)

/**
 * Yields items produced by this stream until the predicate resolves to false.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.tryTakeWhile(predicate: (T) -> Future<Try<Boolean, E>>): TryStreamTakeWhile<T, E> =
    TryStreamTakeWhile.new(this, predicate)

/**
 * Maps the Ok variant of items yielded by this stream.
 */
@HiddenFromObjC
public fun <T, E, R> TryStream<T, E>.mapOk(transform: (T) -> R): Stream<Try<R, E>> =
    this.map { item ->
        when (item) {
            is Try.Ok -> Try.Ok(transform(item.value))
            is Try.Err -> Try.Err(item.error)
        }
    }

/**
 * Maps the Err variant of items yielded by this stream.
 */
@HiddenFromObjC
public fun <T, E, R> TryStream<T, E>.mapErr(transform: (E) -> R): Stream<Try<T, R>> =
    this.map { item ->
        when (item) {
            is Try.Ok -> Try.Ok(item.value)
            is Try.Err -> Try.Err(transform(item.error))
        }
    }

/**
 * Tests whether every item in the stream matches a predicate.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.tryAll(predicate: (T) -> Future<Boolean>): TryAll<T, E> =
    TryAll.new(this, predicate)

/**
 * Tests whether any item in the stream matches a predicate.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.tryAny(predicate: (T) -> Future<Boolean>): TryAny<T, E> =
    TryAny.new(this, predicate)

/**
 * Inspects the Ok value of items yielded by this stream.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.inspectOk(action: (T) -> Unit): Stream<Try<T, E>> =
    this.inspect { item ->
        if (item is Try.Ok) {
            action(item.value)
        }
    }

/**
 * Inspects the Err value of items yielded by this stream.
 */
@HiddenFromObjC
public fun <T, E> TryStream<T, E>.inspectErr(action: (E) -> Unit): Stream<Try<T, E>> =
    this.inspect { item ->
        if (item is Try.Err) {
            action(item.error)
        }
    }
